import { Inter } from 'next/font/google';
import './globals.css';
import HeaderMenu from './components/HeaderMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Next JS 9-2-24',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <HeaderMenu />
        {children}
      </body>
    </html>
  );
}
